CREATE TABLE reviews (
              id bigint not null GENERATED BY DEFAULT AS IDENTITY,
              isbn  VARCHAR(13),
              reviewer VARCHAR(25),
              comment  clob,
              PRIMARY KEY (id)
);
